const data = [
  {
    id: 'uuidv4()',
    first_name: 'Deden',
    last_name: 'Wahid Kusnaedi',
    member_id: 'HP-001',
  },
  {
    id: 'uuidv4()',
    first_name: 'Beny',
    last_name: 'Alam Udi (Rombeng)',
    member_id: 'HP-002',
  },
  {
    id: 'uuidv4()',
    first_name: 'Erry',
    last_name: 'M. Subhan (Uwa)',
    member_id: 'HP-003',
  },
  {
    id: 'uuidv4()',
    first_name: 'Maraja',
    last_name: 'Jeson S. (Econ)',
    member_id: 'HP-004',
  },
  {
    first_name: 'Tri',
    last_name: 'Wahyudi S. (Trige)',
    member_id: 'HP-005',
  },
  {
    id: 'uuidv4()',
    first_name: '6',
    last_name: 'Muhammad Randy Amini (Bung Rendy)',
    member_id: 'HP-006',
  },
  {
    id: 'uuidv4()',
    first_name: '7',
    last_name: 'Lomi Hija (Ome)',
    member_id: 'HP-007',
  },
  {
    id: 'uuidv4()',
    first_name: '8',
    last_name: 'Ursula Ginny Cynthia (Tante Gin)',
    member_id: 'HP-008',
  },
  {
    id: 'uuidv4()',
    first_name: '9',
    last_name: 'Putri Delfitri (Deli/Mak Cik)',
    member_id: 'HP-009',
  },
  {
    id: 'uuidv4()',
    first_name: '10',
    last_name: 'Singgasari Halim',
    member_id: 'HP-010',
  },
  {
    id: 'uuidv4()',
    first_name: '11',
    last_name: 'Ihsan Ilmuddien (Ichan)',
    member_id: 'HP-011',
  },
  {
    id: 'uuidv4()',
    first_name: '12',
    last_name: 'Andrie Joseph (Josh)',
    member_id: 'HP-012',
  },
  {
    id: 'uuidv4()',
    first_name: '13',
    last_name: 'Lie Saw Fa (Sofa)',
    member_id: 'HP-013',
  },
  {
    id: 'uuidv4()',
    first_name: '14',
    last_name: 'Vera Marpaung (Vera Paung)',
    member_id: 'HP-014',
  },
  {
    id: 'uuidv4()',
    first_name: '15',
    last_name: 'Imelda Juliana (Imel/Imeng)',
    member_id: 'HP-015',
  },
  {
    id: 'uuidv4()',
    first_name: '16',
    last_name: 'Maya Maulia (Mayjack)',
    member_id: 'HP-016',
  },
  {
    id: 'uuidv4()',
    first_name: '17',
    last_name: 'Yopie Andromeda',
    member_id: 'HP-017',
  },
  {
    id: 'uuidv4()',
    first_name: '18',
    last_name: 'Kurnia P.D. Jusup (Ai Nyunyuk/Ari)',
    member_id: 'HP-018',
  },
  {
    id: 'uuidv4()',
    first_name: '19',
    last_name: 'Corry Widyastuti (Oi)',
    member_id: 'HP-019',
  },
  {
    id: 'uuidv4()',
    first_name: '20',
    last_name: 'Johnas T. Siahaan (Yonas)',
    member_id: 'HP-020',
  },
  {
    id: 'uuidv4()',
    first_name: '21',
    last_name: 'Alm. Dede Masyhuri (Tunge)',
    member_id: 'HP-021',
  },
  {
    id: 'uuidv4()',
    first_name: '22',
    last_name: 'Rullyanshah Pohan (Rully)',
    member_id: 'HP-022',
  },
  {
    id: 'uuidv4()',
    first_name: '23',
    last_name: 'Ratna Susilowati (Toro)',
    member_id: 'HP-023',
  },
  {
    id: 'uuidv4()',
    first_name: '24',
    last_name: 'Yudi Hersandi (Jimbo)',
    member_id: 'HP-024',
  },
  {
    id: 'uuidv4()',
    first_name: '25',
    last_name: 'Dolly Novaruddin',
    member_id: 'HP-025',
  },
  {
    id: 'uuidv4()',
    first_name: '26',
    last_name: 'Fadil Aziz',
    member_id: 'HP-026',
  },
  {
    id: 'uuidv4()',
    first_name: '27',
    last_name: 'Sapta Yuliandra',
    member_id: 'HP-027',
  },
  {
    id: 'uuidv4()',
    first_name: '28',
    last_name: 'Muhammad Arifin Danika (Ipin)',
    member_id: 'HP-028',
  },
  {
    id: 'uuidv4()',
    first_name: '29',
    last_name: 'A. Jaya Wiranata Kusumah (Kojay)',
    member_id: 'HP-029',
  },
  {
    id: 'uuidv4()',
    first_name: '30',
    last_name: 'Rinny Yunita Katili',
    member_id: 'HP-030',
  },
  {
    id: 'uuidv4()',
    first_name: '31',
    last_name: 'Khususiyah (Sisi)',
    member_id: 'HP-031',
  },
  {
    id: 'uuidv4()',
    first_name: '32',
    last_name: 'Aditiya Samudra (Kardiman)',
    member_id: 'HP-032',
  },
  {
    id: 'uuidv4()',
    first_name: '33',
    last_name: 'Kisworo Ramawijaya (Dewo)',
    member_id: 'HP-033',
  },
  {
    id: 'uuidv4()',
    first_name: '34',
    last_name: 'Margie Laturiuw (Aji)',
    member_id: 'HP-034',
  },
  {
    id: 'uuidv4()',
    first_name: '35',
    last_name: 'Dirga Hadi Ryan',
    member_id: 'HP-035',
  },
  {
    id: 'uuidv4()',
    first_name: '36',
    last_name: 'Fiona (Fine)',
    member_id: 'HP-036',
  },
  {
    first_name: '37',
    last_name: 'Surya',
    member_id: 'HP-037',
  },
  {
    id: 'uuidv4()',
    first_name: '38',
    last_name: 'Rubini (Bibin)',
    member_id: 'HP-038',
  },
  {
    id: 'uuidv4()',
    first_name: '39',
    last_name: 'N.Y.N. Sundayat (Enu)',
    member_id: 'HP-039',
  },
  {
    id: 'uuidv4()',
    first_name: '40',
    last_name: 'Ibroehim (Ibom)',
    member_id: 'HP-040',
  },
  {
    id: 'uuidv4()',
    first_name: '41',
    last_name: 'Eko Aji Wibowo (Ucup)',
    member_id: 'HP-041',
  },
  {
    id: 'uuidv4()',
    first_name: '42',
    last_name: 'Bambang H (Bembeng)',
    member_id: 'HP-042',
  },
  {
    id: 'uuidv4()',
    first_name: '43',
    last_name: 'Yani Sutria (Yani)',
    member_id: 'HP-043',
  },
  {
    id: 'uuidv4()',
    first_name: '44',
    last_name: 'Novie Hanita (Inang)',
    member_id: 'HP-044',
  },
  {
    id: 'uuidv4()',
    first_name: '45',
    last_name: 'Natalia Arlin',
    member_id: 'HP-045',
  },
  {
    id: 'uuidv4()',
    first_name: '46',
    last_name: 'M. Rizky (Bendot)',
    member_id: 'HP-046',
  },
  {
    id: 'uuidv4()',
    first_name: '47',
    last_name: 'Alberta Monica (Berta)',
    member_id: 'HP-047',
  },
  {
    id: 'uuidv4()',
    first_name: '48',
    last_name: 'Astuti Agustina',
    member_id: 'HP-048',
  },
  {
    id: 'uuidv4()',
    first_name: '49',
    last_name: 'Dwi Hendrato',
    member_id: 'HP-049',
  },
  {
    id: 'uuidv4()',
    first_name: '50',
    last_name: 'Andy Arsady',
    member_id: 'HP-050',
  },
  {
    id: 'uuidv4()',
    first_name: '51',
    last_name: 'Yenny Sari',
    member_id: 'HP-051',
  },
  {
    id: 'uuidv4()',
    first_name: '52',
    last_name: 'Audi Ikhsan (Pepeng)',
    member_id: 'HP-052',
  },
  {
    id: 'uuidv4()',
    first_name: '53',
    last_name: 'Ferdinand D.P. (Carol)',
    member_id: 'HP-053',
  },
  {
    id: 'uuidv4()',
    first_name: '54',
    last_name: 'Dimas Ario Wibowo (Kentung)',
    member_id: 'HP-054',
  },
  {
    id: 'uuidv4()',
    first_name: '55',
    last_name: 'Santiaji K',
    member_id: 'HP-055',
  },
  {
    id: 'uuidv4()',
    first_name: '56',
    last_name: 'Achmad Faisal (Ical)',
    member_id: 'HP-056',
  },
  {
    id: 'uuidv4()',
    first_name: '57',
    last_name: 'Dion Novanto',
    member_id: 'HP-057',
  },
  {
    id: 'uuidv4()',
    first_name: '58',
    last_name: 'Muflichun (Lihun)',
    member_id: 'HP-058',
  },
  {
    id: 'uuidv4()',
    first_name: '59',
    last_name: 'Budi Wibowo',
    member_id: 'HP-059',
  },
  {
    id: 'uuidv4()',
    first_name: '60',
    last_name: 'Satrio Wibowo',
    member_id: 'HP-060',
  },
  {
    id: 'uuidv4()',
    first_name: '61',
    last_name: 'Fika Yuanta',
    member_id: 'HP-061',
  },
  {
    id: 'uuidv4()',
    first_name: '62',
    last_name: 'Vidi Putranto (Asbak)',
    member_id: 'HP-062',
  },
  {
    id: 'uuidv4()',
    first_name: '63',
    last_name: 'Arianto Masmel',
    member_id: 'HP-063',
  },
  {
    id: 'uuidv4()',
    first_name: '64',
    last_name: 'Hendro Susetyo',
    member_id: 'HP-064',
  },
  {
    id: 'uuidv4()',
    first_name: '65',
    last_name: 'Ryadi Amdar Yandi',
    member_id: 'HP-065',
  },
  {
    id: 'uuidv4()',
    first_name: '66',
    last_name: 'Hety Nurhayati (Eneng)',
    member_id: 'HP-066',
  },
  {
    id: 'uuidv4()',
    first_name: '67',
    last_name: 'Arya Defri (Dugem)',
    member_id: 'HP-067',
  },
  {
    first_name: '68',
    last_name: 'Fajar Dwinanto (Japrun)',
    member_id: 'HP-068',
  },
  {
    first_name: '69',
    last_name: 'Anton Maladi',
    member_id: 'HP-069',
  },
  {
    first_name: '70',
    last_name: 'Chotmah (cotty)',
    member_id: 'HP-070',
  },
  {
    first_name: '71',
    last_name: 'Sonni Yunharjono (Purba)',
    member_id: 'HP-071',
  },
  {
    first_name: '72',
    last_name: 'Ricky (Gondrong/Once)',
    member_id: 'HP-072',
  },
  {
    first_name: '73',
    last_name: 'Hendra A.P. (Badak)',
    member_id: 'HP-073',
  },
  {
    first_name: '74',
    last_name: 'Marissa Ulfah (Icha)',
    member_id: 'HP-074',
  },
  {
    first_name: '75',
    last_name: 'Happy Perdana (Hepoy)',
    member_id: 'HP-075',
  },
  {
    first_name: '76',
    last_name: 'Adeline Putriani (Alin)',
    member_id: 'HP-076',
  },
  {
    first_name: '77',
    last_name: 'Andi Wiyoko (Tile)',
    member_id: 'HP-077',
  },
  {
    first_name: '78',
    last_name: 'Eka Krisdian (Aconk)',
    member_id: 'HP-078',
  },
  {
    first_name: '79',
    last_name: 'A. Alfian Noor (A Vie)',
    member_id: 'HP-079',
  },
  {
    first_name: '80',
    last_name: 'Ajad S (Embe/Ndoro)',
    member_id: 'HP-080',
  },
  {
    first_name: '81',
    last_name: 'Siska Yunita (Inonk)',
    member_id: 'HP-081',
  },
  {
    id: 'uuidv4()',
    first_name: '82',
    last_name: 'Susandra A (Sandra)',
    member_id: 'HP-082',
  },
  {
    id: 'uuidv4()',
    first_name: '83',
    last_name: 'Maria Dian (Dian)',
    member_id: 'HP-083',
  },
  {
    id: 'uuidv4()',
    first_name: '84',
    last_name: 'Rosataini (Ocha)',
    member_id: 'HP-084',
  },
  {
    id: 'uuidv4()',
    first_name: '85',
    last_name: 'Yusuf Reza (Eja)',
    member_id: 'HP-085',
  },
  {
    id: 'uuidv4()',
    first_name: '86',
    last_name: 'Moh. Deni (Acot)',
    member_id: 'HP-086',
  },
  {
    id: 'uuidv4()',
    first_name: '87',
    last_name: 'Anggie (Onggo-onggo)',
    member_id: 'HP-087',
  },
  {
    id: 'uuidv4()',
    first_name: '88',
    last_name: 'Rendy Ray Kusfadilah (Repit)',
    member_id: 'HP-088',
  },
  {
    id: 'uuidv4()',
    first_name: '89',
    last_name: 'Niky Andrea (Niky)',
    member_id: 'HP-089',
  },
  {
    id: 'uuidv4()',
    first_name: '90',
    last_name: 'Ainiamzia (Aini)',
    member_id: 'HP-090',
  },
  {
    id: 'uuidv4()',
    first_name: '91',
    last_name: 'Putu Neidita W (Putu)',
    member_id: 'HP-091',
  },
  {
    id: 'uuidv4()',
    first_name: '92',
    last_name: 'M. Iqbal Lubis (Ibel)',
    member_id: 'HP-092',
  },
  {
    id: 'uuidv4()',
    first_name: '93',
    last_name: 'Rudi Handian (Kenyal)',
    member_id: 'HP-093',
  },
  {
    id: 'uuidv4()',
    first_name: '94',
    last_name: 'Alfi Agustian (Bau)',
    member_id: 'HP-094',
  },
  {
    id: 'uuidv4()',
    first_name: '95',
    last_name: 'Lidya Silvana (Lidia)',
    member_id: 'HP-095',
  },
  {
    id: 'uuidv4()',
    first_name: '96',
    last_name: 'Yulianti (Cumi)',
    member_id: 'HP-096',
  },
  {
    id: 'uuidv4()',
    first_name: '97',
    last_name: 'Umi Hani (Mihan)',
    member_id: 'HP-097',
  },
  {
    id: 'uuidv4()',
    first_name: '98',
    last_name: 'Yudhy Prasetyo',
    member_id: 'HP-098',
  },
  {
    id: 'uuidv4()',
    first_name: '99',
    last_name: 'Hamzah M. Ihsan (Mije)',
    member_id: 'HP-099',
  },
  {
    id: 'uuidv4()',
    first_name: '100',
    last_name: 'Aldi Fadila (Adul)',
    member_id: 'HP-100',
  },
  {
    id: 'uuidv4()',
    first_name: '101',
    last_name: 'Satria Bintara',
    member_id: 'HP-101',
  },
  {
    id: 'uuidv4()',
    first_name: '102',
    last_name: 'Reditta Cynthia Lavenia',
    member_id: 'HP-102',
  },
  {
    id: 'uuidv4()',
    first_name: '103',
    last_name: 'Aditya Darman',
    member_id: 'HP-103',
  },
  {
    id: 'uuidv4()',
    first_name: '104',
    last_name: 'Hamdan Surya',
    member_id: 'HP-104',
  },
  {
    id: 'uuidv4()',
    first_name: '105',
    last_name: 'Ekalina Khairunnisa',
    member_id: 'HP-105',
  },
  {
    id: 'uuidv4()',
    first_name: '106',
    last_name: 'Vicky Hanggara',
    member_id: 'HP-106',
  },
  {
    id: 'uuidv4()',
    first_name: '107',
    last_name: 'Ikrom Fajar Ilahi (Enday)',
    member_id: 'HP-107',
  },
  {
    id: 'uuidv4()',
    first_name: '108',
    last_name: 'Wiwin Lesmana',
    member_id: 'HP-108',
  },
  {
    id: 'uuidv4()',
    first_name: '109',
    last_name: 'Peter Ames Ronald Ruus',
    member_id: 'HP-109',
  },
  {
    id: 'uuidv4()',
    first_name: '110',
    last_name: 'Harist (Singh)',
    member_id: 'HP-110',
  },
  {
    id: 'uuidv4()',
    first_name: '111',
    last_name: 'Sumayyah Azzahra (Maya)',
    member_id: 'HP-111',
  },
  {
    id: 'uuidv4()',
    first_name: '112',
    last_name: 'Dian Apriliyanti',
    member_id: 'HP-112',
  },
  {
    id: 'uuidv4()',
    first_name: '113',
    last_name: 'Aulia Shifa Fauziah',
    member_id: 'HP-113',
  },
  {
    id: 'uuidv4()',
    first_name: '114',
    last_name: 'Yuni Yosan',
    member_id: 'HP-114',
  },
  {
    id: 'uuidv4()',
    first_name: '115',
    last_name: 'Hilda Awalia Insani',
    member_id: 'HP-115',
  },
  {
    id: 'uuidv4()',
    first_name: '116',
    last_name: 'Asyrafil Muchtar (Rafi)',
    member_id: 'HP-116',
  },
  {
    id: 'uuidv4()',
    first_name: '117',
    last_name: 'Dian Palupi (Mbae)',
    member_id: 'HP-117',
  },
  {
    id: 'uuidv4()',
    first_name: '118',
    last_name: 'Nur Ain Pratiwi (Ain)',
    member_id: 'HP-118',
  },
  {
    id: 'uuidv4()',
    first_name: '119',
    last_name: 'Asmiaty Rizki Amelia (Ameng)',
    member_id: 'HP-119',
  },
  {
    id: 'uuidv4()',
    first_name: '120',
    last_name: 'Ahmad Zakaria Yahya (Jack)',
    member_id: 'HP-120',
  },
  {
    id: 'uuidv4()',
    first_name: '121',
    last_name: 'Muhammad Zuhdi Alwan (Item)',
    member_id: 'HP-121',
  },
  {
    id: 'uuidv4()',
    first_name: '122',
    last_name: 'El Cindy Eskilani',
    member_id: 'HP-122',
  },
  {
    id: 'uuidv4()',
    first_name: '123',
    last_name: 'M. Agung Prabowo (Beler)',
    member_id: 'HP-123',
  },
  {
    id: 'uuidv4()',
    first_name: '124',
    last_name: 'Rivaldo Algivari (Jimbot)',
    member_id: 'HP-124',
  },
  {
    id: 'uuidv4()',
    first_name: '125',
    last_name: 'Fakhri Binangkit (Cai)',
    member_id: 'HP-125',
  },
  {
    id: 'uuidv4()',
    first_name: '126',
    last_name: 'Fennie Oktavirsa (Acil)',
    member_id: 'HP-126',
  },
  {
    id: 'uuidv4()',
    first_name: '127',
    last_name: 'Aggie Rizki Mulyana (Gedong)',
    member_id: 'HP-127',
  },
  {
    id: 'uuidv4()',
    first_name: '128',
    last_name: 'Fajrizal Akbar (Abang)',
    member_id: 'HP-128',
  },
  {
    id: 'uuidv4()',
    first_name: '129',
    last_name: 'Sausan Suhada (Momot)',
    member_id: 'HP-129',
  },
  {
    id: 'uuidv4()',
    first_name: '130',
    last_name: 'Rani Nuraeni (Bintang)',
    member_id: 'HP-130',
  },
  {
    id: 'uuidv4()',
    first_name: '131',
    last_name: 'Seno Tri Mukti (Sipit)',
    member_id: 'HP-131',
  },
  {
    id: 'uuidv4()',
    first_name: '132',
    last_name: 'Febri Rhomadoni (Cangkul)',
    member_id: 'HP-132',
  },
  {
    id: 'uuidv4()',
    first_name: '133',
    last_name: 'Alfrid Dunggio (Po)',
    member_id: 'HP-133',
  },
  {
    id: 'uuidv4()',
    first_name: '134',
    last_name: 'M. Reza Fahlevi (Papakaboy)',
    member_id: 'HP-134',
  },
  {
    id: 'uuidv4()',
    first_name: '135',
    last_name: 'Ilyas Sibghatallah (Si Om)',
    member_id: 'HP-135',
  },
  {
    id: 'uuidv4()',
    first_name: '136',
    last_name: 'Yola Armelia',
    member_id: 'HP-136',
  },
  {
    id: 'uuidv4()',
    first_name: '137',
    last_name: 'Yety Rohmawati Ramadhani',
    member_id: 'HP-137',
  },
  {
    id: 'uuidv4()',
    first_name: '138',
    last_name: 'Munawaroh',
    member_id: 'HP-138',
  },
  {
    id: 'uuidv4()',
    first_name: '139',
    last_name: 'Siti Solehah',
    member_id: 'HP-139',
  },
  {
    id: 'uuidv4()',
    first_name: '140',
    last_name: 'Annisa Kartika',
    member_id: 'HP-140',
  },
  {
    id: 'uuidv4()',
    first_name: '141',
    last_name: 'Ikhlasia Wanodya Tami',
    member_id: 'HP-141',
  },
  {
    id: 'uuidv4()',
    first_name: '142',
    last_name: 'Handiko Putra Warman',
    member_id: 'HP-142',
  },
  {
    id: 'uuidv4()',
    first_name: '143',
    last_name: 'Aliefzhar Mahardika',
    member_id: 'HP-143',
  },
  {
    id: 'uuidv4()',
    first_name: '144',
    last_name: 'Gangsar Yusuf Prastoto',
    member_id: 'HP-144',
  },
  {
    id: 'uuidv4()',
    first_name: '145',
    last_name: 'Arkaf Juliandri',
    member_id: 'HP-145',
  },
  {
    id: 'uuidv4()',
    first_name: '146',
    last_name: 'Albar Moerhamsa',
    member_id: 'HP-146',
  },
  {
    id: 'uuidv4()',
    first_name: '147',
    last_name: 'Latifah Hanim',
    member_id: 'HP-147',
  },
  {
    id: 'uuidv4()',
    first_name: '148',
    last_name: 'Ahmad Farhan Ramadhan',
    member_id: 'HP-148',
  },
  {
    id: 'uuidv4()',
    first_name: '149',
    last_name: 'Angkasa Julio Putra Perdana',
    member_id: 'HP-149',
  },
  {
    id: 'uuidv4()',
    first_name: '150',
    last_name: 'Delfiana Mutiara Illahi',
    member_id: 'HP-150',
  },
  {
    id: 'uuidv4()',
    first_name: '151',
    last_name: 'Astien Anneke Pellokila',
    member_id: 'HP-151',
  },
  {
    id: 'uuidv4()',
    first_name: '152',
    last_name: 'Imam Zarkasyi',
    member_id: 'HP-152',
  },
  {
    id: 'uuidv4()',
    first_name: '153',
    last_name: 'Awalia Rafidha',
    member_id: 'HP-153',
  },
  {
    id: 'uuidv4()',
    first_name: '154',
    last_name: 'Nur Alifah',
    member_id: 'HP-154',
  },
  {
    id: 'uuidv4()',
    first_name: '155',
    last_name: 'Yulia Dwi Rianjani',
    member_id: 'HP-155',
  },
  {
    id: 'uuidv4()',
    first_name: '156',
    last_name: 'Muhammad Mutawali',
    member_id: 'HP-156',
  },
  {
    id: 'uuidv4()',
    first_name: '157',
    last_name: 'Risky Syahputra',
    member_id: 'HP-157',
  },
  {
    id: 'uuidv4()',
    first_name: '158',
    last_name: 'Muhammad Juliandika',
    member_id: 'HP-158',
  },
  {
    id: 'uuidv4()',
    first_name: '159',
    last_name: 'Fikri M. Wafi',
    member_id: 'HP-159',
  },
  {
    id: 'uuidv4()',
    first_name: '160',
    last_name: 'Alyaa Atiqoh',
    member_id: 'HP-160',
  },
  {
    id: 'uuidv4()',
    first_name: '161',
    last_name: 'Putri Oktavia',
    member_id: 'HP-161',
  },
  {
    id: 'uuidv4()',
    first_name: '162',
    last_name: 'M. Taufiq Azzain',
    member_id: 'HP-162',
  },
  {
    id: 'uuidv4()',
    first_name: '163',
    last_name: 'Naufal Rizky Wijaya',
    member_id: 'HP-163',
  },
  {
    id: 'uuidv4()',
    first_name: '164',
    last_name: 'Isyadilah Ghifari',
    member_id: 'HP-164',
  },
  {
    id: 'uuidv4()',
    first_name: '165',
    last_name: 'Desi Sarmila',
    member_id: 'HP-165',
  },
  {
    id: 'uuidv4()',
    first_name: '166',
    last_name: 'Brayen Roma Samuel Sirait',
    member_id: 'HP-166',
  },
  {
    id: 'uuidv4()',
    first_name: '167',
    last_name: 'Muhammad Zulkifli',
    member_id: 'HP-167',
  },
  {
    id: 'uuidv4()',
    first_name: '168',
    last_name: 'Naufal Azmi',
    member_id: 'HP-168',
  },
  {
    id: 'uuidv4()',
    first_name: '169',
    last_name: 'Novry Shendy Pratama',
    member_id: 'HP-169',
  },
  {
    id: 'uuidv4()',
    first_name: '170',
    last_name: 'Fariz Allawi Ghozi',
    member_id: 'HP-170',
  },
  {
    id: 'uuidv4()',
    first_name: '171',
    last_name: 'Tabitha Cristiavane jeanetta',
    member_id: 'HP-171',
  },
  {
    id: 'uuidv4()',
    first_name: '172',
    last_name: 'Alfina Putri Miransyah',
    member_id: 'HP-172',
  },
  {
    id: 'uuidv4()',
    first_name: '173',
    last_name: 'Muhammad Duta Billy',
    member_id: 'HP-173',
  },
  {
    id: 'uuidv4()',
    first_name: '174',
    last_name: 'Arief Nurfareza',
    member_id: 'HP-174',
  },
  {
    id: 'uuidv4()',
    first_name: '175',
    last_name: 'Tri Hartini',
    member_id: 'HP-175',
  },
  {
    id: 'uuidv4()',
    first_name: '176',
    last_name: 'Anugrah Dylan Biantoro',
    member_id: 'HP-176',
  },
  {
    id: 'uuidv4()',
    first_name: '177',
    last_name: 'Riswanti Nur Hajijah',
    member_id: 'HP-177',
  },
]

var fs = require('fs')
const { v4: uuidv4 } = require('uuid')

const format = (data) => {
  const result = data.map((item, index) => {
    var splited = item.last_name.split(' ')

    const id = uuidv4()
    var temp_name = ''
    splited.forEach((el, idx) => idx !== 0 && (temp_name += `${el} `))
    return {
      ...item,
      id: id,
      first_name: item.last_name.split(' ')[0],
      last_name: temp_name,
      gender: 'Male/Female',
      birth_date: '',
      email: '',
      phone: '',
      address: '',
      is_admin: false,
      profile_picture: '',
      password: '123456',
      createdAt: '',
      updatedAt: '',
    }
  })

  fs.writeFile('data-anggota.json', JSON.stringify(result), function (err) {
    if (err) throw err
  })

  return result
}

format(data)
